### ISSUE TITLE
Python is not allowed (Data Science)

### ISSUE THREAD

**Issue by mileserickson** [learn-co/learn-lint#11]
https://learn-linter-ci.herokuapp.com/results/4535

![Screen Shot 2019-08-22 at 3 10 27 PM](https://user-images.githubusercontent.com/68300/63553373-0284db80-c4ef-11e9-82cf-cd6da34d8c9a.png)

**Comment by mathymitchell** [comment]
Seconding Miles call out; receiving repeated error messages regarding Python snippets from the Learn Linter.
