### ISSUE TITLE
Fails without pry installed 

### ISSUE THREAD

**Issue by AspenJames** [learn-co/learn-lint#8]
`learn-lint` fails without `pry` installed: 

> /home/aspen/.rvm/rubies/ruby-2.3.8/lib64/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- pry (LoadError)
        from /home/aspen/.rvm/rubies/ruby-2.3.8/lib64/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/aspen/.rvm/gems/ruby-2.3.8/gems/learn_linter-1.7.3/lib/learn_linter/license_linter.rb:1:in `<top (required)>'
        from /home/aspen/.rvm/gems/ruby-2.3.8/gems/learn_linter-1.7.3/lib/learn_linter.rb:3:in `require_relative'
        from /home/aspen/.rvm/gems/ruby-2.3.8/gems/learn_linter-1.7.3/lib/learn_linter.rb:3:in `<top (required)>'
        from /home/aspen/.rvm/gems/ruby-2.3.8/gems/learn_linter-1.7.3/bin/learn-lint:4:in `require_relative'
        from /home/aspen/.rvm/gems/ruby-2.3.8/gems/learn_linter-1.7.3/bin/learn-lint:4:in `<top (required)>'
        from /home/aspen/.rvm/gems/ruby-2.3.8/bin/learn-lint:23:in `load'
        from /home/aspen/.rvm/gems/ruby-2.3.8/bin/learn-lint:23:in `<main>'
        from /home/aspen/.rvm/gems/ruby-2.3.8/bin/ruby_executable_hooks:24:in `eval'
        from /home/aspen/.rvm/gems/ruby-2.3.8/bin/ruby_executable_hooks:24:in `<main>'

`require 'pry'` found on line 1 of `lib/learn_linter/license_linter.rb`, likely missed during cleanup from development. Suggest removing this line, as `pry` is not necessary as a runtime dependency.
#Staff

**Comment by sgharms** [comment]
I now own this repo and will be committing a massively refactored code base. Closing.
